#!/bin/bash

alias ..='cd ..;'
alias .2='..; ..;'
alias .3='.2; ..;'
alias .4='.3; ..;'
alias .5='.4; ..;'
alias .6='.5; ..;'

alias ..2='.2'
alias ..3='.3'
alias ..4='.4'
alias ..5='.5'
alias ..6='.6'
