#!/bin/bash
# be verbose when files are the same
alias diff='diff -s --color=always'

xmldiff() {
	if ! command -v xmllint >/dev/null; then
		echo "please install xmllint" >&2
		return 20
	fi
	if [[ $# -ne 2 ]]; then
		echo "please pass exactly 2 XML files to this tool" >&2;
		return 21
	fi

	diff <(sed -e 's/</\n</g' "$1" | sed -e '1d' | xmllint --c14n -) \
	     <(sed -e 's/</\n</g' "$2" | sed -e '1d' | xmllint --c14n -)
}
