#!/bin/bash

alias ga='git add'
alias gc='git commit'
alias gch='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --show-signature'
alias glg='git log --oneline --graph'
alias gpl='git pull --rebase'
alias gps='git push'
alias gs='git status -s'
alias gsa='git stash save' #add
alias gsd='git stash show' #diff
alias gsl='git stash list'
alias gss='git stash show'
alias gst='git stash'
