#!/bin/bash
# enable color support of ls and also add handy aliases
if [[ ${platform:?} == "OSX" ]]; then
	lscolor="-G"
else
	lscolor="--color=auto"
fi

alias ls="ls $lscolor -F"
alias ll="ls $lscolor -alFh"
alias la="ls $lscolor -A"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

