#!/bin/bash

if command -v nvim &>/dev/null;
then
  alias vim='nvim'
fi

alias vimrc='vim -c "cd ~/dotfiles/neovim/.config/nvim" -p ~/dotfiles/neovim/.config/nvim/init.vim ~/dotfiles/neovim/.config/nvim/plugins/*.vim'

alias initvim='vimrc'

alias nvmi=nvim
