#!/bin/bash

# these are meant for interactive use only

alias .='ls -hCF --color=auto'
alias a=ansible-playbook
#alias b
#alias c
alias d=docker
alias D=_docker-compose
#alias e
#alias f
#alias g=git
#alias h
#alias i
#alias j
#alias k
alias l='ls -CF'

# run django's manage.py within pipenv
alias m='find "$(dirname "$(find $(git rev-parse --show-toplevel) -name "Pipfile")")" -name "manage\\.py" | xargs -I MANAGE_PY pipenv run MANAGE_PY'
#alias n
#alias o
alias p='pipenv run'
#alias q
alias r=rustup
# ssh seems short enough :-)
alias s='sudo systemctl'
alias t=tmux
alias u='systemctl --user'
#alias v
#alias w
alias x=xdg-open
#alias y
#alias z

_docker-compose() {
	name="$(sed -nre "s/^x-project-name: (\"|P)(.*)(\1)$/\2/p" docker-compose.yml)"
	# default to directory name, just like docker-compose
	project_name="${name:-"$(pwd | xargs basename)"}"
	docker-compose --project-name "$project_name" $@
}
