#!/bin/bash

# these are meant for interactive use only

alias .='ls -hCF --color=auto'
alias a=ansible-playbook
#alias b
#alias c
alias d=docker
alias D=docker-compose
#alias e
#alias f
#alias g=git
#alias h
#alias i
#alias j
#alias k
alias l='ls -CF'
#alias m
#alias n
#alias o
alias p='pipenv run'
#alias q
alias r=rustup
# ssh seems short enough :-)
alias s='sudo systemctl'
alias t=tmux
alias u='systemctl --user'
#alias v
#alias w
alias x=xdg-open
#alias y
#alias z
