#!/bin/bash

# set 256 colors and unicode support
alias tmux='$(which tmux) -2 -u'

function tn() {
	tmux new-session -A -D -d -s $@
}

function tl() {
	tmux list-sessions $@
}

function ta() {
	if tmux has-session -t "$@" &>/dev/null; then
		tmux switch-client -t $@
	else
		tmux new-session -A -D -d -s $@
		tmux switch-client -t $@
	fi
}
