#!/bin/bash
thisfile="${BASH_SOURCE[0]}"
thisdir="$(dirname "${thisfile}" )"
preexec_file="${thisdir}/preexec.sh"

if [ ! -f "$preexec_file" ];
then
    # Pull down our file from GitHub and write it to our home directory as a hidden file.
    curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o "$preexec_file"
fi

if [ -f "$preexec_file" ];
then
    source "$preexec_file"
fi
