#!/bin/bash

# set 256 colors and unicode support
alias tmux="tmux -2 -u"
alias tn="tmux new-session -A -D -d -s"
alias tl="tmux list-sessions"
function ta() {
	tmux attach-session -d -t $@ 2>/dev/null || tmux switch-client -t $@
}
