#!/bin/bash
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

escstart='\['
escend='\]'

_color_black="$(tput setaf 0)"
_color_red="$(tput setaf 1)"
_color_green="$(tput setaf 2)"
_color_yellow="$(tput setaf 3)"
_color_blue="$(tput setaf 4)"
_color_purple="$(tput setaf 5)"
_color_cyan="$(tput setaf 6)"
_color_white="$(tput setaf 7)"


_light_black="$(tput setaf 8)"
_light_red="$(tput setaf 9)"
_light_green="$(tput setaf 10)"
_light_yellow="$(tput setaf 11)"
_light_blue="$(tput setaf 12)"
_light_purple="$(tput setaf 13)"
_light_cyan="$(tput setaf 14)"
_light_white="$(tput setaf 15)"

_bold="$(tput bold)"

text_black="${escstart}${_color_black}${escend}"
text_red="${escstart}${_color_red}${escend}"
text_green="${escstart}${_color_green}${escend}"
text_yellow="${escstart}${_color_yellow}${escend}"
text_blue="${escstart}${_color_blue}${escend}"
text_purple="${escstart}${_color_purple}${escend}"
text_cyan="${escstart}${_color_cyan}${escend}"
text_white="${escstart}${_color_white}${escend}"


bold_black="${escstart}${_bold}${_color_black}${escend}"
bold_red="${escstart}${_bold}${_color_red}${escend}"
bold_green="${escstart}${_bold}${_color_green}${escend}"
bold_yellow="${escstart}${_bold}${_color_yellow}${escend}"
bold_blue="${escstart}${_bold}${_color_blue}${escend}"
bold_purple="${escstart}${_bold}${_color_purple}${escend}"
bold_cyan="${escstart}${_bold}${_color_cyan}${escend}"
bold_white="${escstart}${_bold}${_color_white}${escend}"

underline_black="${escstart}${underline}${_color_black}${escend}"
underline_red="${escstart}${underline}${_color_red}${escend}"
underline_green="${escstart}${underline}${_color_green}${escend}"
underline_yellow="${escstart}${underline}${_color_yellow}${escend}"
underline_blue="${escstart}${underline}${_color_blue}${escend}"
underline_purple="${escstart}${underline}${_color_purple}${escend}"
underline_cyan="${escstart}${underline}${_color_cyan}${escend}"
underline_white="${escstart}${underline}${_color_white}${escend}"

background_black="${escstart}${background}${_color_black}${escend}"
background_red="${escstart}${background}${_color_red}${escend}"
background_green="${escstart}${background}${_color_green}${escend}"
background_yellow="${escstart}${background}${_color_yellow}${escend}"
background_blue="${escstart}${background}${_color_blue}${escend}"
background_purple="${escstart}${background}${_color_purple}${escend}"
background_cyan="${escstart}${background}${_color_cyan}${escend}"
background_white="${escstart}${background}${_color_white}${escend}"


textreset="${escstart}$(tput sgr0)${escend}"   # Text Reset

hostcolor="\[$(tput setaf $hostnum)\]"
usercolor="\[$(tput setaf $usernum)\]"

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

