#!/bin/bash

function get_git_status() {
	# Grab the git dirty and git behind
	dirty_branch="$(parse_git_dirty)"
	branch_ahead="$(parse_git_ahead)"
	branch_behind="$(parse_git_behind)"

	# Iterate through all the cases and if it matches, then echo
	if [[ "$dirty_branch" == 1 && "$branch_ahead" == 1 && "$branch_behind" == 1 ]]; then
		echo "$dirty_unpushed_unpulled_symbol"
	elif [[ "$branch_ahead" == 1 && "$branch_behind" == 1 ]]; then
		echo "$unpushed_unpulled_symbol"
	elif [[ "$dirty_branch" == 1 && "$branch_ahead" == 1 ]]; then
		echo "$dirty_unpushed_symbol"
	elif [[ "$branch_ahead" == 1 ]]; then
		echo "$unpushed_symbol"
	elif [[ "$dirty_branch" == 1 && "$branch_behind" == 1 ]]; then
		echo "$dirty_unpulled_symbol"
	elif [[ "$branch_behind" == 1 ]]; then
		echo "$unpulled_symbol"
	elif [[ "$dirty_branch" == 1 ]]; then
		echo "$dirty_synced_symbol"
	else # clean
		echo "$synced_symbol"
	fi
}
