#!/bin/bash
get_git_info () {
    # Grab the branch
    branch="$(get_git_branch)"

    # If there are any branches
    if [[ "$branch" != "" ]]; then
	# Echo the branch
	output="$branch"

	# Add on the git status
	output="$output$(get_git_status)"

	# Echo our output
	echo -n "$output"
    fi
}
