#!/bin/bash
is_branch1_behind_branch2 () {
	# $ git log origin/master..master -1
	# commit 4a633f715caf26f6e9495198f89bba20f3402a32
	# Author: Todd Wolfson <todd@twolfson.com>
	# Date:   Sun Jul 7 22:12:17 2013 -0700
	#
	#     Unsynced commit

	# Find the first log (if any) that is in branch1 but not branch2
	first_log="$(git log $1..$2 -1 2> /dev/null)"

	# Exit with 0 if there is a first log, 1 if there is not
	[[ -n "$first_log" ]]
}
