#!/bin/bash

function git_branch_info() {
	if [[ -n "$(git rev-parse HEAD 2>/dev/null)" ]]; then
		append_line "⛕  ${bold_yellow}" \
		| append "$(get_git_info)" \
		| append "$(get_git_progress)" \
		| append "${textreset}"
	else
		input
	fi
}

