#!/bin/bash
function prompt_command {
	#  prompt_x is where to position the cursor to write the clock
	local prompt_x
	prompt_x=$(tput cols)-6
	#  Move up one; not sure why we need to do this, but without this, I always
	#  got an extra blank line between prompts
	tput sc
	tput cup 0 ${prompt_x}
	tput setaf 4 ; tput bold
	echo -n "["
	tput setaf 1
	echo -n "$(date +%H%M)"
	tput setaf 4 ; tput bold
	echo -n "]"
	tput rc
}
