#!/bin/bash
if ! command -v thefuck &>/dev/null;
then
  echo "thefuck not installed; please install 'thefuck' via apt, homebrew or pip" >&2
else
  alias fuck='eval $(thefuck $(fc -ln -1) )'
  alias kut='fuck'
fi
