#!/bin/bash


## default aliases in ubuntu's bashrc

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias grep='grep --color=auto'

lscolor="--color=auto"
if [[ $platform == "OSX" ]]; then
	lscolor="-G"
fi
alias ls="ls -F $lscolor"
alias la="ls -A $lscolor"
alias ll="ls -AlhF $lscolor";

unset lscolor

alias_path="$bash_abs_path/.config/bash/aliases.d"

for alias_file in $(ls "$alias_path");
do
  source "$alias_path/$alias_file"
done

unset alias_path
