#!/bin/bash
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if command -v pandoc >/dev/null 2>&1; then
  eval "$(pandoc --bash-completion)"
fi

if command -v kubectl >/dev/null 2>&1; then
  eval "$(kubectl completion bash)"
fi

if command -v minikube >/dev/null 2>&1; then
  eval "$(minikube completion bash)"
fi
