#!/bin/bash

PATH="$PATH"

# loop over files, starting with 00-system
for file in $(find "${BASH_SOURCE[0]}.d/" -type f);
do
    if [[ -f "$file" ]]; then

        # we read the entire file in an arry, one line per entry
        readarray -t lines < "$file"

        # we loop backwards over the lines
        # prepending each line to the path
        for (( lineindex = ${#lines[@]}; lineindex; )); do
            PATH="${lines[--lineindex]}:$PATH"
        done
    fi
done

eval PATH="$PATH"
