#!/bin/bash

for file in $(find "${BASH_SOURCE[0]}.d/" -type f);
do
    if [[ -f "$file" ]];
    then
	source "$file"
    fi
done

PS2='$(tput ed)> '
PS4='+ '

store_history() {
	history -a
	history -c
	history -r
}

precmd_functions+=(get_exit_code)
precmd_functions+=(display_prompt)
precmd_functions+=(store_history)

wipe_prompt() {
    # save cursor position
    tput sc
    # go to beginnig of previous line
    tput cuu 1
    # overwrite char
    echo -n "━"
    if [[ "$last_status" -ne 0 ]]; then
        tput cuu 1
        tput cub 1
        echo -n "┗"
    fi
    # restore position
    tput rc
    # wipe until end of screen
    tput ed
}

preexec_functions+=(wipe_prompt)
