#!/bin/bash
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#find platform
case $(uname) in
	"Darwin") platform="OSX" ;;
	"linux") platform="linux" ;;
	"Linux") platform="linux" ;;
	*) echo "unknown platform" >&2 platform="unknown";;
esac

# some default type
session_type=local/shell

# check if running inside tmux
if [ ! -z "$TMUX" ]; then
  session_type=remote/tmux

# check if user is connected over ssh
elif [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  session_type=remote/ssh

else
  case $(ps -o comm= -p $PPID) in
    # check if parent process is SSH
    sshd|*/sshd) session_type=remote/ssh;;
  esac
fi

